"""
Example usage of the GeneratedVoiceover table for saving voiceover URLs
"""

from models.db_models import GeneratedVoiceover, get_session
from sqlmodel import Session, select
from datetime import datetime
import json

def save_voiceover_to_db(
    user_id: str,
    voice_id: str,
    voice_name: str,
    text_content: str,
    filename: str,
    file_url: str,
    script_id: str = None,
    video_id: str = None,
    speed: float = 1.0,
    pitch: float = 1.0,
    volume: float = 0.8,
    tone: str = None,
    file_size: int = None,
    duration_seconds: float = None,
    ai_provider: str = None,
    ai_model: str = None
) -> GeneratedVoiceover:
    """
    Save a generated voiceover to the database
    
    Args:
        user_id: ID of the user who generated the voiceover
        voice_id: ID of the voice used (from SelectAIVoices table)
        voice_name: Human-readable name of the voice
        text_content: The text that was converted to speech
        filename: The actual filename (e.g., "voiceover_demo-script-123_1757707084.wav")
        file_url: Full URL to access the file (e.g., "/api/audio/voiceover_demo-script-123_1757707084.wav")
        script_id: Optional reference to ScriptGeneration table
        video_id: Optional reference to Video table
        speed: Playback speed (default: 1.0)
        pitch: Voice pitch (default: 1.0)
        volume: Audio volume (default: 0.8)
        tone: Voice tone setting
        file_size: File size in bytes
        duration_seconds: Audio duration in seconds
        ai_provider: Provider used (e.g., "replicate", "elevenlabs", "openai")
        ai_model: Specific model used
    
    Returns:
        GeneratedVoiceover: The created voiceover record
    """
    
    with Session(engine) as session:
        voiceover = GeneratedVoiceover(
            user_id=user_id,
            script_id=script_id,
            video_id=video_id,
            voice_id=voice_id,
            voice_name=voice_name,
            text_content=text_content,
            speed=speed,
            pitch=pitch,
            volume=volume,
            tone=tone,
            filename=filename,
            file_url=file_url,
            file_size=file_size,
            duration_seconds=duration_seconds,
            ai_provider=ai_provider,
            ai_model=ai_model,
            status="completed"
        )
        
        session.add(voiceover)
        session.commit()
        session.refresh(voiceover)
        
        return voiceover

def get_user_voiceovers(user_id: str) -> list[GeneratedVoiceover]:
    """
    Get all voiceovers generated by a specific user
    
    Args:
        user_id: ID of the user
        
    Returns:
        List of GeneratedVoiceover records
    """
    
    with Session(engine) as session:
        statement = select(GeneratedVoiceover).where(GeneratedVoiceover.user_id == user_id)
        voiceovers = session.exec(statement).all()
        return voiceovers

def get_voiceovers_by_script(script_id: str) -> list[GeneratedVoiceover]:
    """
    Get all voiceovers generated for a specific script
    
    Args:
        script_id: ID of the script
        
    Returns:
        List of GeneratedVoiceover records
    """
    
    with Session(engine) as session:
        statement = select(GeneratedVoiceover).where(GeneratedVoiceover.script_id == script_id)
        voiceovers = session.exec(statement).all()
        return voiceovers

def get_voiceovers_by_video(video_id: str) -> list[GeneratedVoiceover]:
    """
    Get all voiceovers generated for a specific video
    
    Args:
        video_id: ID of the video
        
    Returns:
        List of GeneratedVoiceover records
    """
    
    with Session(engine) as session:
        statement = select(GeneratedVoiceover).where(GeneratedVoiceover.video_id == video_id)
        voiceovers = session.exec(statement).all()
        return voiceovers

def update_voiceover_status(voiceover_id: str, status: str, error_message: str = None):
    """
    Update the status of a voiceover (useful for tracking processing status)
    
    Args:
        voiceover_id: ID of the voiceover to update
        status: New status ("processing", "completed", "failed")
        error_message: Error message if status is "failed"
    """
    
    with Session(engine) as session:
        statement = select(GeneratedVoiceover).where(GeneratedVoiceover.id == voiceover_id)
        voiceover = session.exec(statement).first()
        
        if voiceover:
            voiceover.status = status
            voiceover.updated_at = datetime.now()
            
            if error_message:
                voiceover.error_message = error_message
                
            session.add(voiceover)
            session.commit()

# Example usage:
if __name__ == "__main__":
    from models.db_models import engine
    
    # Example: Save a new voiceover
    voiceover = save_voiceover_to_db(
        user_id="user123",
        voice_id="af_alloy",
        voice_name="Alloy",
        text_content="Welcome to our amazing video tutorial about Python programming.",
        filename="voiceover_demo_script_123_1234567890.wav",
        file_url="/api/audio/voiceover_demo_script_123_1234567890.wav",
        script_id="script_456",
        speed=1.1,
        pitch=1.0,
        volume=0.85,
        file_size=1024000,  # 1MB
        duration_seconds=15.5,
        ai_provider="openai",
        ai_model="tts-1-alloy"
    )
    
    print(f"Saved voiceover with ID: {voiceover.id}")
    print(f"File URL: {voiceover.file_url}")
    
    # Example: Get all voiceovers for a user
    user_voiceovers = get_user_voiceovers("user123")
    print(f"Found {len(user_voiceovers)} voiceovers for user123")